version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_app_db

volumes:
  mysql: {}
